upstream flask_cluster {
    server web:8005;
}

server {
    listen 80;

    # 1. Cấu hình để Nginx tự phục vụ file tĩnh (ảnh, css, js)
    location /static/ {
        # Chỉ định đường dẫn tới thư mục static bên trong container Nginx
        alias /app/static/;

        # Tùy chọn: Cho phép trình duyệt lưu cache file tĩnh trong 30 ngày để web tải nhanh hơn
        expires 30d;
        add_header Cache-Control "public, max-age=2592000";
    }

    # 2. Tất cả các request khác (đăng nhập, xem bài viết...) mới đẩy cho Flask
    location / {
        proxy_pass http://flask_cluster;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}