apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-forum-dashboard
  namespace: default
  labels:
    # Cực kỳ quan trọng: Đây là dấu hiệu để Grafana Sidecar biết đây là Dashboard
    grafana_dashboard: "1"
data:
  flask-forum-dashboard.json: |-
    {
      "title": "Flask Forum Production Dashboard",
      "uid": "flask-forum-dynamic",
      "schemaVersion": 38,
      "timezone": "browser",
      "refresh": "10s",
      "editable": true,
      "templating": {
        "list": [
          {
            "name": "DS_PROMETHEUS",
            "type": "datasource",
            "query": "prometheus",
            "label": "Data Source",
            "multi": false,
            "includeAll": false
          },
          {
            "name": "App_Name",
            "type": "custom",
            "query": "flask-forum,flask-forum-staging,flask-forum-prod",
            "label": "Application Name",
            "current": { "text": "flask-forum", "value": "flask-forum" }
          }
        ]
      },
      "panels": [
        {
          "type": "timeseries",
          "title": "Sử dụng CPU các node (%)",
          "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
          "datasource": "${DS_PROMETHEUS}",
          "targets": [
            { "expr": "(1 - avg by (instance)(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])))*100", "refId": "A" }
          ]
        },
        {
          "type": "timeseries",
          "title": "CPU pod app (mCPU)",
          "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
          "datasource": "${DS_PROMETHEUS}",
          "targets": [
            { "expr": "sum by (pod)(rate(container_cpu_usage_seconds_total{container!='',container=\"${App_Name}\"}[5m])*1000)", "refId": "A" }
          ]
        },
        {
          "type": "timeseries",
          "title": "Tiêu thụ Ram của node (%)",
          "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
          "datasource": "${DS_PROMETHEUS}",
          "targets": [
            { "expr": "sum by (instance) ((node_memory_MemTotal_bytes-node_memory_MemAvailable_bytes)/node_memory_MemTotal_bytes)*100", "refId": "A" }
          ]
        },
        {
          "type": "timeseries",
          "title": "Tiêu thụ Ram của pod-container (MB)",
          "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
          "datasource": "${DS_PROMETHEUS}",
          "targets": [
            { "expr": "sum by (pod) (container_memory_working_set_bytes{container!='',container=\"${App_Name}\"}/1024/1024)", "refId": "A" }
          ]
        },
        {
          "type": "timeseries",
          "title": "Request rate 5 phút gần nhất (req/s)",
          "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
          "datasource": "${DS_PROMETHEUS}",
          "targets": [
            { "expr": "sum by (pod) (rate(flask_forum_http_requests_total{container=\"${App_Name}\", container!=\"\", pod=~\"${App_Name}-.*\"}[5m]))", "refId": "A" }
          ]
        }
      ]
    }