{
 "title": "Flask Forum Production Dashboard",
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "App_Name",
    "label": "Application Name",
    "query": "flask-forum,flask-forum-staging,flask-forum-prod"
   }
  ]
 },
 "panels": [
  {
   "title": "Sử dụng CPU các node (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(1 - avg by (instance)(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])))*100"
    }
   ]
  },
  {
   "title": "CPU pod app (mCPU)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod)(rate(container_cpu_usage_seconds_total{container!='',container=\"${App_Name}\"}[5m])*1000)"
    }
   ]
  },
  {
   "title": "Tiêu thụ Ram của node (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (instance) ((node_memory_MemTotal_bytes-node_memory_MemAvailable_bytes)/node_memory_MemTotal_bytes)*100"
    }
   ]
  },
  {
   "title": "Tiêu thụ Ram của pod-container (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{container!='',container=\"${App_Name}\"}/1024/1024)"
    }
   ]
  },
  {
   "title": "Request rate 5 phút gần nhất (req/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by (pod) (rate(flask_forum_http_requests_total{container=\"${App_Name}\", container!=\"\", pod=~\"${App_Name}-.*\"}[5m]))"
    }
   ]
  }
 ]
}