name: ForumWebCicd

on:
  push:
    branches:
       ["main", "master"]
  pull_request:
    branches:
       ["main", "master"]

#job1: Check code
jobs:
  check_code:
    runs-on: ubuntu-latest

    steps:
      - name: Kéo mã nguồn về máy chủ
        uses: actions/checkout@v4

      - name: Thiết lập Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'

      - name: cài flake8
        run: pip install flake8

      - name: Quét mã nguồn bằng Flake8
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

# Job 2: Build, test and push image to registry
  build_test_and_push_image:
    needs: check_code
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Kéo mã nguồn về máy chủ
        uses: actions/checkout@v4


      - name: Kiểm tra phiên bản Docker & Docker Compose
        run: |
          docker --version
          docker compose version
          
      - name: Giải mã file bảo mật từ Base64
        run: echo "${{ secrets.ENV_B64 }}" | base64 --decode > .env

      - name: Build và khởi chạy hệ thống bằng Docker Compose
        run: |
          docker compose up -d --build --scale web=2
          docker compose -f monitoring.yaml up -d

      - name: Chờ hệ thống khởi động (30 giây)
        run: sleep 30


      - name: fill sql data
        run: docker exec -it forum_sql_server /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${{secrets.DB_PASS} -C -i /ForumWEB.sql

      - name: Kiểm tra trạng thái các Container
        run: docker compose ps

      - name: chờ fill dữ liệu vào sql server
        run: sleep 20

      - name: Kiểm tra trạng thái các Container
        run: docker compose ps

      - name: Kiểm tra kết nối Web (Ping thử Nginx)
        run: curl -f http://localhost:8005 || exit 1

      - name: In ra Log của Flask App (để debug nếu cần)
        run: docker compose logs web

      - name: Đăng nhập vào GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: push image
        run: docker push ghcr.io/huynongquoc05/forumweb_deployment:latest

      - name: Dọn dẹp (Tắt container)
        run: docker compose down


#  # Job 3: Deploy
#  deploy:
#    needs: build_test_and_push_image
#    runs-on: ubuntu-latest
#    steps:
#      - name: kết nối server
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SERVER_HOST }}
#          username: ${{ secrets.SERVER_USER }}
#          key: ${{ secrets.SERVER_SSH_KEY }}
#          port: 8901
#          script: |
#            cd /home/huynq/ForumWEB_Deployment
#            git pull origin main
#            docker compose down
#            docker pull ghcr.io/huynongquoc05/forumweb_deployment:latest
#            docker compose up -d --build --scale web=2
#            docker exec -it forum_sql_server /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${{secrets.DB_PASS} -C -i /ForumWEB.sql
#            sleep 50
#            curl -f http://localhost:8005 || exit 1
##
##





